-- MySQL Script generated by MySQL Workbench
-- Mon Aug 24 17:00:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`PROVEIDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROVEIDOR` (
  `id_proveidor` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `adreca` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proveidor`),
  UNIQUE INDEX `id_proveidor_UNIQUE` (`id_proveidor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COLOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COLOR` (
  `id_color` INT NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_color`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MUNTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MUNTURA` (
  `id_muntura` INT NOT NULL,
  `material` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_muntura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VIDRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIDRE` (
  `id_vidre` INT NOT NULL,
  `tipus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_vidre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEATS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEATS` (
  `id_empleat` INT NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  `cognom` VARCHAR(20) NOT NULL,
  `dni` VARCHAR(10) NOT NULL,
  `telefon` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_empleat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTS` (
  `id_client` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `Adreca` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data` DATETIME NOT NULL,
  `recomanat` VARCHAR(45) NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REGISTRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REGISTRE` (
  `id_registre` INT NOT NULL,
  `id_ulleres` INT NULL,
  `id_client` INT NULL,
  `id_empleat` INT NULL,
  `EMPLEATS_id_empleat` INT NOT NULL,
  `CLIENTS_id_client` INT NOT NULL,
  PRIMARY KEY (`id_registre`, `EMPLEATS_id_empleat`, `CLIENTS_id_client`),
  INDEX `fk_REGISTRE_EMPLEATS1_idx` (`EMPLEATS_id_empleat` ASC),
  INDEX `fk_REGISTRE_CLIENTS1_idx` (`CLIENTS_id_client` ASC),
  CONSTRAINT `fk_REGISTRE_EMPLEATS1`
    FOREIGN KEY (`EMPLEATS_id_empleat`)
    REFERENCES `mydb`.`EMPLEATS` (`id_empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REGISTRE_CLIENTS1`
    FOREIGN KEY (`CLIENTS_id_client`)
    REFERENCES `mydb`.`CLIENTS` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ULLERES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ULLERES` (
  `id_ulleres` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `graduacio` DECIMAL(4,2) NOT NULL,
  `id_muntura` INT NOT NULL,
  `id_color` INT NOT NULL,
  `id_vidre` INT NOT NULL,
  `preu` DECIMAL(5,2) NOT NULL,
  `PROVEIDOR_id_proveidor` INT NOT NULL,
  `COLOR_id_color` INT NOT NULL,
  `MUNTURA_id_muntura` INT NOT NULL,
  `VIDRE_id_vidre` INT NOT NULL,
  `REGISTRE_id_registre` INT NOT NULL,
  PRIMARY KEY (`id_ulleres`, `PROVEIDOR_id_proveidor`, `COLOR_id_color`, `MUNTURA_id_muntura`, `VIDRE_id_vidre`, `REGISTRE_id_registre`),
  INDEX `fk_ULLERES_PROVEIDOR_idx` (`PROVEIDOR_id_proveidor` ASC),
  INDEX `fk_ULLERES_COLOR1_idx` (`COLOR_id_color` ASC),
  INDEX `fk_ULLERES_MUNTURA1_idx` (`MUNTURA_id_muntura` ASC),
  INDEX `fk_ULLERES_VIDRE1_idx` (`VIDRE_id_vidre` ASC),
  INDEX `fk_ULLERES_REGISTRE1_idx` (`REGISTRE_id_registre` ASC),
  CONSTRAINT `fk_ULLERES_PROVEIDOR`
    FOREIGN KEY (`PROVEIDOR_id_proveidor`)
    REFERENCES `mydb`.`PROVEIDOR` (`id_proveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ULLERES_COLOR1`
    FOREIGN KEY (`COLOR_id_color`)
    REFERENCES `mydb`.`COLOR` (`id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ULLERES_MUNTURA1`
    FOREIGN KEY (`MUNTURA_id_muntura`)
    REFERENCES `mydb`.`MUNTURA` (`id_muntura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ULLERES_VIDRE1`
    FOREIGN KEY (`VIDRE_id_vidre`)
    REFERENCES `mydb`.`VIDRE` (`id_vidre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ULLERES_REGISTRE1`
    FOREIGN KEY (`REGISTRE_id_registre`)
    REFERENCES `mydb`.`REGISTRE` (`id_registre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
